### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by NRiedinger** [jsGanttImproved/jsgantt-improved#271]
Hello,

first of all, thanks for this awesome gantt chart!

My question is the following:
Is it possible to properly change the font size?

It it's not supported by your side, I'd highly suggest it as a feature because 
the default size is a bit small in my opinion.

**Comment by mariohmol** [comment]
Hi!

You can change via css, for example

```
.gtasktable span {
    font-size: 20px;
}
```

**Comment by NRiedinger** [comment]
Thanks for the quick answer.

However, I had to use different selectors to successfully change font size, like:

```css
ng-gantt td {
    font-size: 12px !important;
}

ng-gantt td > div {
    font-size: 12px !important;
}
```
